import java.awt.event.ActionEvent;

public class gradeCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GradeJFrame
     */
    public gradeCalculator() {
        initComponents();
        setTitle("Grade Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        st_id = new javax.swing.JLabel();
        stu_idTF = new javax.swing.JTextField();
        st_name = new javax.swing.JLabel();
        stud_nameTF = new javax.swing.JTextField();
        section = new javax.swing.JLabel();
        school_name = new javax.swing.JLabel();

        phy = new javax.swing.JLabel();
        chem = new javax.swing.JLabel();
        math = new javax.swing.JLabel();
        eng = new javax.swing.JLabel();

        physicsGradeTF = new javax.swing.JTextField();
        chemistryGradeTF = new javax.swing.JTextField();
        mathematicsGradeTF = new javax.swing.JTextField();
        englishGradeTF = new javax.swing.JTextField();
        total_gradeTF = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gpaTF = new javax.swing.JTextField();
        gpaTF.setEditable(false);
        physicsEvalTF = new javax.swing.JTextField();
        physicsEvalTF.setEditable(false);
        chemistryEvalTF = new javax.swing.JTextField();
        chemistryEvalTF.setEditable(false);
        mathEvalTF = new javax.swing.JTextField();
        mathEvalTF.setEditable(false);
        englishEvalTF = new javax.swing.JTextField();
        englishEvalTF.setEditable(false);
        sectionCB = new javax.swing.JComboBox<>();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        st_id.setText("Student ID:");



        st_name.setText("Student Name:");

        section.setText("Section:");

        school_name.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        school_name.setForeground(new java.awt.Color(255, 51, 51));
        school_name.setText("BATANGAS STATE UNIVERSITY");

        phy.setText("Physics");

        chem.setText("Chemistry");

        math.setText("Mathematics");

        eng.setText("English");

        total_gradeTF.setEditable(false);

        total.setText("Total Grade:");

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(ActionEvent evt) {
                exitActionPerformed(evt);

            }
        });

        jLabel1.setText("GPA");

        gpaTF.setEditable(false);


        physicsEvalTF.setEditable(false);

        chemistryEvalTF.setEditable(false);

        mathEvalTF.setEditable(false);

        englishEvalTF.setEditable(false);

        sectionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSCPE 2201", "BSCPE 2202", "BSCPE 2203", "BSCPE 2204", "BSCPE 2205" }));
        sectionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(school_name)
                                .addContainerGap(161, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(st_name)
                                        .addComponent(st_id)
                                        .addComponent(eng, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(phy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(chem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(math))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(stud_nameTF)
                                        .addComponent(stu_idTF)
                                        .addComponent(physicsGradeTF)
                                        .addComponent(chemistryGradeTF)
                                        .addComponent(mathematicsGradeTF)
                                        .addComponent(englishGradeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(physicsEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chemistryEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mathEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(englishEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(total)
                                                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(enter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(total_gradeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(gpaTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sectionCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(school_name)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(st_id)
                                        .addComponent(stu_idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(section)
                                        .addComponent(sectionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(stud_nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(st_name))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phy)
                                        .addComponent(physicsGradeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(total_gradeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(total)
                                        .addComponent(physicsEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chem)
                                        .addComponent(chemistryGradeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chemistryEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(math)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(mathematicsGradeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(enter)
                                                .addComponent(clear)
                                                .addComponent(exit)
                                                .addComponent(mathEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(eng)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(englishGradeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(englishEvalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //Exit Button function
    private void exitActionPerformed(java.awt.event.ActionEvent evt){
        dispose();
    }
    
    //Clear Button function
    private void clearActionPerformed(java.awt.event.ActionEvent evt){

        // Clearing the input text fields
        st_name.setText("");
        stu_idTF.setText("");
        physicsGradeTF.setText("");
        chemistryGradeTF.setText("");
        mathematicsGradeTF.setText("");
        englishGradeTF.setText("");

        // Clear the evaluation text fields, GPA and total grade
        physicsEvalTF.setText("");
        chemistryEvalTF.setText("");
        mathEvalTF.setText("");
        englishEvalTF.setText("");
        gpaTF.setText("");
        total_gradeTF.setText("");
    }

    //Enter button function
    private void enterActionPerformed(java.awt.event.ActionEvent evt) {
        String physicsScore, chemistryScore, mathematicsScore, englishScore;
        double total;
        double gpa = 0;

        physicsScore= physicsGradeTF.getText();
        chemistryScore = chemistryGradeTF.getText();
        mathematicsScore = mathematicsGradeTF.getText();
        englishScore = englishGradeTF.getText();

        double physics = Double.parseDouble(physicsScore);
        double chemistry = Double.parseDouble(chemistryScore);
        double mathematics = Double.parseDouble(mathematicsScore);
        double english = Double.parseDouble(englishScore);

        total = (physics + chemistry + mathematics + english)/400*100;

        if (physics >= 90) {
            physicsEvalTF.setText("A");
            gpa = gpa + 1.00;
        } else if (physics >=80 && physics < 90) {
            physicsEvalTF.setText("B");
            gpa = gpa + 1.5;
        } else if (physics >=70 && physics < 80) {

            physicsEvalTF.setText("C");
            gpa = gpa + 2.00;
        } else if (physics >=60 && physics < 70) {
            physicsEvalTF.setText("D");
            gpa = gpa + 3.00;
        } else {
            physicsEvalTF.setText("F");
            gpa = gpa + 5.00;
        }

        if (chemistry >= 90) {
            chemistryEvalTF.setText("A");
            gpa = gpa + 1.00;
        } else if (chemistry >=80 && chemistry < 90) {
            chemistryEvalTF.setText("B");
            gpa = gpa + 1.5;
        } else if (chemistry >=70 && chemistry < 80) {
            chemistryEvalTF.setText("C");
            gpa = gpa + 2.00;
        } else if (chemistry >=60 && chemistry < 70) {
            chemistryEvalTF.setText("D");
            gpa = gpa + 3.00;
        } else {
            chemistryEvalTF.setText("F");
            gpa = gpa + 5.00;
        }

        if (mathematics >= 90) {
            mathEvalTF.setText("A");
            gpa = gpa + 1.00;
        } else if (mathematics >=80 && mathematics < 90) {
            mathEvalTF.setText("B");
            gpa = gpa + 1.5;
        } else if (mathematics >=70 && mathematics < 80) {
            mathEvalTF.setText("C");
            gpa = gpa + 2.00;
        } else if (mathematics >=60 && mathematics < 70) {
            mathEvalTF.setText("D");
            gpa = gpa + 3.00;
        } else {
            mathEvalTF.setText("F");
            gpa = gpa + 5.00;
        }

        if (english >= 90) {
            englishEvalTF.setText("A");
            gpa = gpa + 1.00;
        } else if (english >=80 && english < 90) {
            englishEvalTF.setText("B");
            gpa = gpa + 1.5;
        } else if (english >=70 && english < 80) {
            englishEvalTF.setText("C");
            gpa = gpa + 2.00;
        } else if (english >=60 && english < 70) {
            englishEvalTF.setText("D");
            gpa = gpa + 3.00;
        } else {
            englishEvalTF.setText("F");
            gpa = gpa + 5.00;
        }


        gpa = gpa / 4;

        gpaTF.setText(Double.toString(gpa));
        total_gradeTF.setText(Double.toString(total));








    }//GEN-LAST:event_enterActionPerformed


    private void sectionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gradeCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chem;
    private javax.swing.JTextField chemistryGradeTF;
    private javax.swing.JButton clear;
    private javax.swing.JTextField chemistryEvalTF;
    private javax.swing.JTextField englishEvalTF;
    private javax.swing.JLabel eng;
    private javax.swing.JTextField englishGradeTF;
    private javax.swing.JButton enter;
    private javax.swing.JButton exit;
    private javax.swing.JTextField gpaTF;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> sectionCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel math;
    private javax.swing.JTextField mathematicsGradeTF;
    private javax.swing.JTextField mathEvalTF;
    private javax.swing.JLabel phy;
    private javax.swing.JTextField physicsGradeTF;
    private javax.swing.JTextField physicsEvalTF;
    private javax.swing.JLabel school_name;
    private javax.swing.JLabel section;
    private javax.swing.JLabel st_id;
    private javax.swing.JLabel st_name;
    private javax.swing.JTextField stu_idTF;
    private javax.swing.JTextField stud_nameTF;
    private javax.swing.JLabel total;
    private javax.swing.JTextField total_gradeTF;
    // End of variables declaration//GEN-END:variables
}
